# Generated by Django 4.1.3 on 2022-12-12 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_departmentprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='allocated_budget',
            field=models.IntegerField(default=0),
        ),
    ]
